name: CI

on: [push, pull_request]

jobs:
  linter_and_test:
    runs-on: ubuntu-16.04
    strategy:
      max-parallel: 10
      matrix:
        python-version: [3.6, 3.7]
        pytorch-version: [1.0.1, 1.1, 1.2, 1.3, 1.3.1]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install dependencies
        run: |
          # install python modules
          python -m pip install --upgrade pip
          pip install -q -U numpy
          pip install -q torch==${{ matrix.pytorch-version }} -f https://download.pytorch.org/whl/cpu/stable.html
          pip install -q -e .
          pip install -q -e .[test]
          # install shell check
          wget https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
          tar -xvf shellcheck-stable.linux.x86_64.tar.xz
      - name: ShellCheck
        run: |
          export PATH=shellcheck-stable:$PATH
          find egs -name "*.sh" | while read line; do shellcheck -x --shell=bash -P $(dirname $line) ${line}; done
      - name: Flake8
        run: |
          flake8 parallel_wavegan
      - name: Pytest
        run: |
          pytest test
